### ISSUE TITLE
Camera doesn't work on Samsung

### ISSUE THREAD

**Issue by AlexTararenko** [Andrew0000/ImagePickerPlus#2]
Hi! I tested the camera functionality on the Samsung Galaxy A52 running Android 13 and encountered an issue. When attempting to take a photo, there was no confirmation button to return the result to the application, only a preview of the taken photo was available.

**Comment by Andrew0000** [comment]
Hi Alex. Thank you for this finding. 
I have no Samsung device so I can't really test it but I have an idea how it can be fixed. 
I made some changes, could you please try a new 1.0.2 version?

**Comment by AlexTararenko** [comment]
Hi! I've discovered the actual issue. It is not related to the code, but rather the UI of the Samsung Camera app. Specifically, the buttons are just transparent with black text, making them incredibly difficult to notice. I was only able to see them in landscape mode.
